name: CI

on:
  pull_request:
    branches:
      - main
      - dev
  push:
    branches:
      - dev
      - main

jobs:
  build:
    runs-on: macos-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Show Xcode version
        run: xcodebuild -version

      - name: Run project CI script
        run: ./scripts/ci.sh
